name: Test Build

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: push repo
        run: |
          git config --global "tommaso.ramella90@gmail.com"
          git config --global "tommella90"
          git add .
          git commit -m "update version"
          git push

      - name: version control
        run: |
          python version_control.py
        
          

#     - name: push repo
#        push:
#          branches:
#            - main






